version: "3.0"
debug: true
testing: false
csrf_enabled: true
secret_key: 'thisissecret'
sqlalchemy_database_uri: "postgresql:///flask_dropbox"
upload_folder: '/path/to/the/uploads'
allowed_extensions: ['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif']
apispec_swagger_url: '/swagger'