version: '2.1'
services:
  postgres:
    restart: always
    image: postgres:9.5
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=flask_dropbox
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - postgres
    command:
      bash -c 'flask db init && flask db migrate && flask db upgrade'
    entrypoint: ["python", "main.py","runserver"]