version: '3'
services:
  app:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: bash -c "python3 main.py && flask db init && flask db migrate && flask db upgrade"
  postgres:
    image: postgres:9.5
    env_file:
      - conf/postgres.env
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    tty: true