version: '3'
services:
  app:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: bash -c "python3 main.py"
  postgres:
    image: postgres:9.5
    env_file:
      - conf/postgres.env
    ports:
      - 5432