"""empty message

Revision ID: 683f71447277
Revises: 62b10e8f4aee
Create Date: 2019-01-31 10:26:03.987909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683f71447277'
down_revision = '62b10e8f4aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stripe', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stripe', sa.Column('user_id', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
