"""empty message

Revision ID: b0faf3ede9ed
Revises: 6963faca8a4d
Create Date: 2019-01-16 02:39:08.015316

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b0faf3ede9ed'
down_revision = '6963faca8a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'file', ['data'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='unique')
    # ### end Alembic commands ###
